const TRIBUTE_THEME_VARIANT_KEY = 'TRIBUTE_THEME_VARIANT';
const TRIBUTE_AUTH_TOKEN = 'TRIBUTE_AUTH_TOKEN';
const TRIBUTE_AUTH_DATA = 'TRIBUTE_AUTH_DATA';
const SERVER_BASE_URL = 'http://localhost:5000';

export const CONSTANTS = {TRIBUTE_THEME_VARIANT_KEY, SERVER_BASE_URL, TRIBUTE_AUTH_TOKEN, TRIBUTE_AUTH_DATA};
